language: android

env:
  matrix:
    - ANDROID_TARGET=android-27  ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-27
